const CHANGE_PRODUCT_MODE = {
    CREATE_PRODUCT: 1,
    UPDATE_PRODUCT: 2,
    QUICKCOPY_PRODUCT: 3,
    CREATE_PRODUCT_GROUP: 4,
    UPDATE_PRODUCT_GROUP: 5,
    QUICKCOPY_PRODUCT_GROUP: 6,
}

export {
    CHANGE_PRODUCT_MODE
}